### PR TITLE
Fix file system issues with convertPoundToKilogram.

### LINKED ISSUE #484: Fix filesystem issues with convertPoundToKilogram
At least on Mac, there are two files for converting pound to kilogram, convertPoundToKilogram and convertPoundtoKilogram. They are competing for attention. The "to" file needs to go and be replaced with the "To" file. Tests need to be updated.

### PR DESCRIPTION
**Pull request by kenhkelly**
Closes #484 

Fix file system issues with convertPoundToKilogram.
Add skeleton method for circumferenceOfACircle.

- [x] Running `yarn lint` does not trigger any linter errors
- [X] The test of the method you have fixed is passing
- [X] You have written a new skeleton method for someone else to work on!
- [X] You have written tests to accompany your skeleton method

### CODE REVIEW

**Comment by kenhkelly** [comment]
@ktilcu I added more tests.

**Comment by ktilcu** [comment]
Thanks for the quick response! Happy Hacktoberfest! 🎃

**Comment by ktilcu** [comment]
It would help us if you made an issue for you new method too. Thank you!

**Comment by kenhkelly** [comment]
Created an issue for the new circumferenceOfACircle method. Cheers

**Pull request merged**
