### PR TITLE
Code for firstUniqueChar and skeleton&test from mode.js

### PR DESCRIPTION
**Pull request by erisitohang**
Make sure these boxes are checked before submitting this pull request~!~ Thank you!!

- [x] The test of the method you have fixed is passing
- [x] You have written a new skeleton method for someone else to work on!

### CODE REVIEW

**Comment by erisitohang** [comment]
Hi @BlakeGuilloud , I have fixed the conflict

**Comment by BlakeGuilloud** [comment]
Hey @erisitohang !! I hate doing this to you twice in one day, but it looks like some conflicts have arisen! We updated our development process to include linting as well, so you will need to adjust some of the code to follow our style. I'll be updating the READMEs to reflect these changes at some point tonight. Thanks for the contribution- and sorry to make you resolve more conflicts.

**Comment by erisitohang** [comment]
all checked :)

**Comment by cjhaviland** [comment]
#164 Didn't realized as someone submitted a PR for this as I pulled new code, so I just refactored it. Hope that is alright.

**Pull request merged**
