### PR TITLE
Fix & Implement regexReplace

### PR DESCRIPTION
**Pull request by buoyantair**
- [x] Running `yarn lint` does not trigger any linter errors
- [x] The test of the method you have fixed is passing
- [x] You have written a new skeleton method for someone else to work on!
- [x] You have written tests to accompany your skeleton method

### CODE REVIEW

**Comment by ktilcu** [comment]
@buoyantair Thanks for the contribution! can you rebase to collect some of the recent changes and then I will merge for you! Happy Hacktobering!

**Comment by buoyantair** [comment]
@ktilcu Sure!

**Comment by ktilcu** [comment]
Also tagging #185 for this so we can close that issue accordingly.

**Comment by buoyantair** [comment]
Woops, I'm having trouble with rebase 😅 Looking at docs and trying again! sorry!

**Comment by ktilcu** [comment]
You can edit that file during rebase to remove the arrows and delete and keep the code you want. Then commit!

**Comment by buoyantair** [comment]
I'm trying! The problem is I already committed! 😞

**Comment by buoyantair** [comment]
Okay now it works! @ktilcu

**Comment by ktilcu** [comment]
Shoot we lost your new skeleton. Go ahead and add it to your next PR @buoyantair !

**Pull request merged**
