### PR TITLE
fixes #353

### LINKED ISSUE #353: Fix convertDegreesToRadians method
There is currently a method called `convertDegreesToRadians` that lives in `/lib/convertDegreesToRadians.js`.
It is incomplete and needs to be fixed!

`convertDegreesToRadians ` should convert degrees to radians. If the parameter is not a number the method should throw an error.

### Acceptance Criteria:
1. Running `yarn test convertDegreesToRadians ` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

### PR DESCRIPTION
**Pull request by jsjain007**
Closes #theRelatedIssueNumber

- [] Running `yarn lint` does not trigger any linter errors
- [] The test of the method you have fixed is passing
- [] You have written a new skeleton method for someone else to work on!
- [] You have written tests to accompany your skeleton method

### CODE REVIEW

**Comment by jsjain007** [comment]
oh OK so with these pull requests I should be adding 1 more template and undo the changes in template?

**Comment by jsjain007** [comment]
@BlakeGuilloud  I have resolved the conflicts and added an issue as well. Could you please review my pull request. Thanks. :)

**Comment by BlakeGuilloud** [comment]
Hey @jsjain007 ! Looks like there are still some conflicting files in the `isArray` method.

**Comment by jsjain007** [comment]
sorry for the mess, can I create a new pull request ?

**Comment by BlakeGuilloud** [comment]
Sure.

**Comment by jsjain007** [comment]
could you please review pull request #377 and thanks for the patience.

**Comment by BlakeGuilloud** [comment]
Ok @jsjain007 - I have merged in #377 - Could you either clean up this branch or create a new PR with your other methods? thanks!

**Comment by jsjain007** [comment]
sure will create new pull requests for other methods as well.

**Comment by BlakeGuilloud** [comment]
Cool- as you do that, would you mind closing out this PR when it is no longer useful to you? Thanks!

**Comment by ktilcu** [comment]
@jsjain007 still need this? I'm going to close it.

**Pull request closed without merging**
