### PR TITLE
Ganon logo version 2

### PR DESCRIPTION
**Pull request by csleong98**
version 2 of ganon

### CODE REVIEW

**Comment by BlakeGuilloud** [comment]
@csleong98 !!!! This is awesome! I'm torn between the two designs you have submitted so far. I'm going to go ahead and merge this in. Would you be ok with me putting one of them in our README?

**Comment by csleong98** [comment]
Yes the second its always the better one to be displayed in the README. thx a lot

**Comment by BlakeGuilloud** [comment]
Thank YOU!!!

**Comment by BlakeGuilloud** [comment]
You are an awesome individual! Thank you so much for this.

image

**Comment by csleong98** [comment]
Thank you! Look forward for future collaboration and contribution.

**Pull request merged**
