### PR TITLE
Fix gcd

### PR DESCRIPTION
**Pull request by hariaakash**
- [x] Running `yarn lint` does not trigger any linter errors
- [x] The test of the method you have fixed is passing
- [x] You have written a new skeleton method for someone else to work on!
- [x] You have written tests to accompany your skeleton method

### CODE REVIEW

**Comment by BlakeGuilloud** [comment]
Thanks @hariaakash !! We really appreciate your contribution. Going to go ahead and merge this in, but if you get a chance, we are trying to encourage our contributors to create the Issue for the skeleton method they have created. Thanks!!

**Comment by hariaakash** [comment]
@BlakeGuilloud Here it is https://github.com/BlakeGuilloud/ganon/issues/223.
Moreover can I know if I can work on more of these, just because am bored 😛

**Comment by BlakeGuilloud** [comment]
@hariaakash ! Feel free to work on your own skeleton methods if you would like! We just ask that for each method you resolve (even if it's your own), you provide a new method for someone else.

I already gave your Issue to someone else, but if you want to create new methods, feel free!!

You can make them as Skeleton Methods or full fledged solutions, but for each solution you provide, just make sure you create a new skeleton :D

**Comment by hariaakash** [comment]
@BlakeGuilloud on it bro !!

**Pull request merged**
