### PR TITLE
Validating method additions with existing test cases.

### PR DESCRIPTION
**Pull request by akram-rameez**
I didnt think it would be this simple, but now Travis CI also runs tests on new method additions, and validates it.

I did the following by 
- getting diff from master
- getting only filename which did not have a test case associated to it.
- run testcase on that method.

### CODE REVIEW

**Comment by akram-rameez** [comment]
Referring #304

**Comment by ktilcu** [comment]
@akram-rameez Looks like Travis disagrees. :(

**Comment by akram-rameez** [comment]
Nah man, this won't work on this, since the only edit made on this is the Travis file. Diff says to run jest "", so naturally this will break.

For new cases, it'll take the diff and run jest <methodName>.

Tried and tested on my fork.

**Comment by ktilcu** [comment]
so @akram-rameez just merge it? What if you added a solved case for a sec?

**Comment by akram-rameez** [comment]
so the test checks if a case is solved, a new skeleton is added for a new question, and test cases are added for the new skeleton.

If you run the tests directly on master, method name will be empty, so it'll run all test cases. 

I've taken certain assumptions, like any new PR will always have these files:
- <methodName>.js
- <skeleton>.js
- <skeleton>.test.js

It could go wrong for any other edge case. I'm open to discuss. If you're happy with this, merge away 👍

**Comment by ktilcu** [comment]
Oh i just had a thought. Can the build actually require the skeleton method and fail if it's not there so we don't have to keep reminding people? I can merge this and wait for that. That would be super helpful.

**Comment by akram-rameez** [comment]
Is there any way of forcing people to avoid touching the test case? Because that's how I decide which file to run tests on. 

I could also run tests on all the *.js files, and see if tests either completely fail, or completely pass. It seems hackier, so I'm not really comfortable with this solution.

> Oh I just had a thought. Can the build actually require the skeleton method and fail if it's not there so we don't have to keep reminding people? I can merge this and wait for that. That would be super helpful.

Oh yeah, I clearly need to make it more verbose, so people can understand why the build failed much more easily. I'll write a script file, and run that instead of making a one-liner on the Travis yml.

Any ideas?

**Pull request merged**
