### PR TITLE
Csleong98 ganon logo version 1

### PR DESCRIPTION
**Pull request by csleong98**
Just trying to learn creating pull request from my fork because I have been doing it wrong for the whole time, sry for the inconvenience caused.

### CODE REVIEW

**Comment by andreasgruenh** [comment]
How about you try to include the logo into the README? If you are using Visual Studio Code, press ctrl+shift+p and type markdown to open the markdown preview.

**Comment by csleong98** [comment]
I will tomorrow morning but i am using Atom(I'll search for the solution). BTW how is the logo any improvements?

**Comment by andreasgruenh** [comment]
I really like it! Lets wait for what @BlakeGuilloud has to say :)

**Comment by csleong98** [comment]
its only version 1 so it will be more simpler as the time passes before Oct ends

**Comment by BlakeGuilloud** [comment]
Incredible. You are awesome!!

**Comment by csleong98** [comment]
Thx guys will work on a better design.

**Pull request merged**
