### PR TITLE
Dynamically load modules

### PR DESCRIPTION
**Pull request by ktilcu**
This helps reduce merge conflicts and the amount of work to add a new
method.

@BlakeGuilloud

- [x] Running `yarn lint` does not trigger any linter errors
- [x] The test of the method you have fixed is passing
- [x] You have written a new skeleton method for someone else to work on!
- [x] You have written tests to accompany your skeleton method

### CODE REVIEW

**Comment by BlakeGuilloud** [comment]
I love this @ktilcu !! Really cool stuff. Do you mind updating the contributing.md? There should be a section in there about exporting your method from 'lib/index.js'.

Thanks!!

**Comment by ktilcu** [comment]
Done.

**Comment by andreasgruenh** [comment]
I thin we should adapt the usage section of the Readme after this change.
For Frontend projects, it is no longer possible to import from index.js, but for bundle size it is better to directly import functions anyways so it is not bad. 
The user should then use  `import compose from 'ganon/compose';`

**Comment by ktilcu** [comment]
@BlakeGuilloud @andreasgruenh yeah I got it.

**Pull request merged**
