### PR TITLE
fixed select method

### LINKED ISSUE #385: Fix select method
There is currently a method called `select` that lives in `/lib/select.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test select` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

### PR DESCRIPTION
**Pull request by sanatankc**
Closes #385

- [x] Running `yarn lint` does not trigger any linter errors
- [x] The test of the method you have fixed is passing
- [ ] You have written a new skeleton method for someone else to work on!
- [ ] You have written tests to accompany your skeleton method

### CODE REVIEW

**Comment by sanatankc** [comment]
Oh sorry! I have read contributing guidelines, must have missed this. I will create new skeleton method  in few hours.

**Comment by sanatankc** [comment]
Hey @BlakeGuilloud. Sorry for bothering you. I am new to testing just want to know what is the library you are using for testing other than mocha. I mean for assertion, those `expect` function?

**Comment by BlakeGuilloud** [comment]
Hey @sanatankc ! We are using Jest

**Comment by ktilcu** [comment]
@sanatankc I'm going to close this PR for now just to reduce the noise we have here. As soon as you add those new files to the PR you can reopen it! Thanks!

**Pull request closed without merging**
