### PR TITLE
Fixed isInteger function and added additional tests.

### LINKED ISSUE #278: Fix isInteger function
There is currently a method called `isInteger` that lives in `/lib/isInteger.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test isInteger` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

### PR DESCRIPTION
**Pull request by coymeetsworld**
Closes #278

- [x] Running `yarn lint` does not trigger any linter errors
- [x] The test of the method you have fixed is passing
- [] You have written a new skeleton method for someone else to work on!
- [x] You have written tests to accompany your skeleton method

### CODE REVIEW

**Comment by amoradi** [comment]
@coymeetsworld @ktilcu 
`Number.isInteger()` is not supported in Internet Explorer: @coymeetsworld https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/isInteger

You might defensively try their ^^^ polyfill method (unless we're including an IE polyfill somewhere)

**Comment by ktilcu** [comment]
We are not including a polyfill. Good catch.

**Comment by coymeetsworld** [comment]
Hey guys, have you had a chance to look at my updated pull requests? Anything else I need to do?

**Comment by BlakeGuilloud** [comment]
@coymeetsworld ! nice. I'll go ahead and merge this in. Thanks!

**Pull request merged**
