### PR TITLE
fix once.js, once.test.js and add manhattanDistance.js, manhattanDist…

### PR DESCRIPTION
**Pull request by stillNovice**
…ance.test.js

Closes #theRelatedIssueNumber

- [] Running `yarn lint` does not trigger any linter errors
- [] The test of the method you have fixed is passing
- [] You have written a new skeleton method for someone else to work on!
- [] You have written tests to accompany your skeleton method

### CODE REVIEW

**Comment by stillNovice** [comment]
Hi @ktilcu , @BlakeGuilloud  I don't know why my skeleton function is also considered in the build, and hence the build is failing. Could you please check whats going wrong...

**Comment by ktilcu** [comment]
@stillNovice @akram-rameez made a change to the build process. I want to point this out to him so he can look at it and I will revert the commit shortly. Thanks!

**Comment by ktilcu** [comment]
I have reverted that commit. If you rebase and push then you should be good to go!

**Comment by akram-rameez** [comment]
@ktilcu just saw the file changes. Since the test was supposed to run on the method *without the test case* and @stillNovice modified the test case, it got the case undefined. 

Nonetheless, I'll try making the build a little bit more flexible, and give more verbose descriptions.

**Comment by BlakeGuilloud** [comment]
@stillNovice ! Ship it!! You mind creating a new Issue for your skelly? Thanks!

**Pull request merged**
