### PR TITLE
Feature/throttle (#652)

### LINKED ISSUE #652: Fix throttle function
There is currently a method called `throttle` that lives in `/lib/throttle.js`.
It is incomplete and needs to be fixed!

Throttle takes a callback function and wait time (ms) and returns a throttled version of the callback.
A throttled function can only invoke the original callback as frequently as is specified by the 'wait' argument.

### Acceptance Criteria:
1. Running `yarn test throttle` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

### PR DESCRIPTION
**Pull request by josephmcasey**
Add isSymbol method
Closes #652

- [x] Running `yarn lint` does not trigger any linter errors
- [x] The test of the method you have fixed is passing
- [x] You have written a new skeleton method for someone else to work on!
- [x] You have written tests to accompany your skeleton method

### CODE REVIEW

**Comment by josephmcasey** [comment]
Contingent on a successful pull request, I will create an issue for the isSymbol method.

Looking forward to a review and thoughts from any passerbys.

**Comment by josephmcasey** [comment]
Shoot, looks like `An error occurred while generating the build script.` It looks like all of the of package scripts run correctly for me. Any thoughts on why this happened?

**Comment by josephmcasey** [comment]
```
{
  "language": "node_js",
  "node_js": "node",
  "script": [
    "npm run lint"
  ],
  "group": "stable",
  "dist": "trusty",
  "os": "linux"
}
```

**Comment by kylevv** [comment]
Haha, that is not a helpful error.  Travis may been taking a nap.
Maybe someone can trigger a rebuild to see the problem is gone.

**Comment by BlakeGuilloud** [comment]
Fixed the build. Going to pull this down and take a look. Thanks!

**Pull request merged**
