### PR TITLE
Fixed hex2dec and added prime

### LINKED ISSUE #623: Fix hex2dec method
There is currently a method called `hex2dec` that lives in `/lib/hex2dec.js`.
It is incomplete and needs to be fixed!

The method takes in a hex string and converts it to a decimal number.

### Acceptance Criteria:
1. Running `yarn test hex2dec` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

### PR DESCRIPTION
**Pull request by masterhuck**
Fixed hex2dec and added prime

Closes #623

- [x] Running `yarn lint` does not trigger any linter errors
- [x] The test of the method you have fixed is passing
- [x] You have written a new skeleton method for someone else to work on!
- [x] You have written tests to accompany your skeleton method

### CODE REVIEW

**Comment by masterhuck** [comment]
Hey @BlakeGuilloud, sure. Should I open a second pull request with another commit or how do you usually change something like this. Pretty new to this sorry.

**Comment by BlakeGuilloud** [comment]
@masterhuck ! No worries. You should be able to just push up to your fork with the name changes and it will be reflected in this pull request.

**Comment by masterhuck** [comment]
@BlakeGuilloud thanks a lot. Changed the name.

**Comment by masterhuck** [comment]
Sure, opened issue #655.

**Pull request merged**
