### PR TITLE
Implement distanceN.

### LINKED ISSUE #784: Fix distanceN
There is currently a method called `distanceN` that lives in `/lib/distanceN.js`.
It is incomplete and needs to be fixed!

### Acceptance Criteria:
1. Running `yarn test distanceN.test.js` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

### PR DESCRIPTION
**Pull request by crhallberg**
Closes #784

- [x] Running `yarn lint` does not trigger any linter errors
- [x] The test of the method you have fixed is passing
- [x] You have written a new skeleton method for someone else to work on!
- [x] You have written tests to accompany your skeleton method

### CODE REVIEW

**Comment by crhallberg** [comment]
I haven't added a new skeleton method, but I do think that mapArray isn't working the way most developers would expect a map function to work. You can see this in the test where the callback is iterating through an entire array, not just an element: https://github.com/BlakeGuilloud/ganon/blob/master/test/mapArray.test.js#L6

**Comment by mtso** [comment]
@crhallberg it would be helpful to show how you think it should work by updating the test to fail the existing implementation. 

Just to clarify, though: are you expecting mapArray to work like Array.map?

**Comment by crhallberg** [comment]
mapObject is iterating over the items: https://github.com/BlakeGuilloud/ganon/blob/master/lib/mapCollection.js#L23

I think it may be a case of the implementer misinterpreting the doc comment at the top of the file: "Implement your own map function, obviously without using JavaScript's map function"

**Comment by crhallberg** [comment]
I mean... I'm probably taking this too seriously...

**Comment by ktilcu** [comment]
@crhallberg  thanks for pointing that out! i made a PR to fix it.

**Comment by crhallberg** [comment]
Added a skeleton to pass this on. I think we're ready to go!

**Pull request merged**
