### PR TITLE
Complete floor(), add random(), add Travis CI config, remove .DS_Store

### PR DESCRIPTION
**Pull request by shawnhwei**

### CODE REVIEW

**Comment by BlakeGuilloud** [comment]
Thanks @shawnhwei !!

**Comment by shawnhwei** [comment]
FYI I kept the other implementation of floor() that was already merged, it's obviously more inspired. `package-lock.json` was added to .gitignore and I removed it, not sure if there is some reason it was added.

**Comment by BlakeGuilloud** [comment]
In regards to the package-lock.json, we are moving towards favoring the `yarn` library instead. I am currently working on a new readme to include this information. Thanks!

**Comment by shawnhwei** [comment]
Oops, then it will need to be re-committed. Also I'm sure you're aware but you need to turn on the repo on Travis before it will actually start running.

**Pull request closed without merging**
