### PR TITLE
Added skeleton for isEven.js

### PR DESCRIPTION
**Pull request by melissa3000**
Make sure these boxes are checked before submitting this pull request~!~ Thank you!!

- [x] The test of the method you have fixed is passing
- [x] You have written a new skeleton method for someone else to work on!
(This is the new skeleton for my other pull request - min.js)

### CODE REVIEW

**Comment by BlakeGuilloud** [comment]
Looks good! If you could please write an `isEven.test.js` file in the test directory and include appropriate tests, I'll merge this in along with your other pull request, thanks!

**Comment by melissa3000** [comment]
I've somehow created too many threads here, but I think the test has been added successfully for isEven.test.js

**Comment by BlakeGuilloud** [comment]
@melissa3000 if you click on the "Files Changed" tab in this PR, you will see that they aren't any tests included. Maybe you didn't push it up?

**Comment by melissa3000** [comment]
Every time I make a change, it creates a new number. The test is in #105. Sorry, I have no idea why I can't get it to add to my existing pull request.

**Comment by BlakeGuilloud** [comment]
@melissa3000 I'm not sure what is going on with your branching either. Hmmm I don't mind the extra pull requests, so don't worry about continue to try to sort out the issue.

**Comment by BlakeGuilloud** [comment]
Resuming convo here: https://github.com/BlakeGuilloud/ganon/issues/97

**Pull request closed without merging**
