### PR TITLE
Fix for the product method to be left variadic #366.

### LINKED ISSUE #366: Fix the product method to be left variadic
There is currently a method called `product` that lives in `/lib/product.js`.
It is incomplete and needs to be fixed!

Take a look at #283. The `product` method qualifies for variadic treatment. It should be able to take variable number of arguments, both numeric types and castable to numeric types or a mix of both. It may even take arrays of such types.

For hint on how to achieve that, take a look at #365. 

### Acceptance Criteria:
1. Running `yarn test product` results in tests passing.
2. You have written a skeleton method for someone else to work on.
3. You have written tests surrounding your skeleton method.
4. Running `yarn lint` does not print any errors to the console!
5. Optional: write one or two more tests surrounding the method you are solving to account for potential edge cases.

### Please include the skeleton of a new method + an accompanying test for someone else to work on at the time of creating a pull request! A pull request will most likely be denied if it does not contain a skeleton method for someone else to work on! For more information, please read the [Contributing Guide](https://github.com/BlakeGuilloud/ganon/blob/master/CONTRIBUTING.md).

Thank you so much for your contribution!

### PR DESCRIPTION
**Pull request by JJEEGG2211**
Added hypotenuse method skeleton.

Closes #366

- [x] Running `yarn lint` does not trigger any linter errors
- [x] The test of the method you have fixed is passing
- [x] You have written a new skeleton method for someone else to work on!
- [x] You have written tests to accompany your skeleton method

### CODE REVIEW

**Comment by babhishek21** [comment]
It'd be great to have a few more test cases for the `product` method. For example, you could have a mix of booleans with integers and even arrays of those. What about doubles/floating types? 

Hints: 
+ Boolean `true` gets cast to 1, `false` gets cast to 0 as integers. 
+ You can look at the tests for `sum` to get an idea.

**Comment by ktilcu** [comment]
@JJEEGG2211 Wow! Your first contribution on github. Way to go! @babhishek21 has a good point. If you would like to do that then please go for it and I can merge this. If you've had enough already then we can merge whats here and open an issue to update those tests. Thanks for taking the time to work with us!

**Comment by JJEEGG2211** [comment]
Hi @ktilcu and @babhishek21! Alright I'll do that then. Thanks very much!

**Comment by JJEEGG2211** [comment]
Hi @ktilcu and @babhishek21, I updated the tests for the product.js please review it. Thanks so much! I need 3 more! 😄

**Comment by babhishek21** [comment]
@JJEEGG2211 The tests are pretty good. Cheers! Not sure what has happened with all the other commits showing up in this PR. 

A little bit of advice: Follow these best practices the next time you are contributing to a repo on github:
1. Fork that repo
2. Make a branch from the `master` (or equivalent mainline) branch. Commit all your feature related work into this `feature` branch.
3. Push all relevant commits to your feature branch. Maybe even do periodic sync from upstream (the original repo) to stay updated.
4. Create a PR to merge your ` feature` branch to the original repo's `master` (or equivalent mainline) branch. Github is very good at automatically suggesting this every time you push to your `feature` branch.

**Comment by JJEEGG2211** [comment]
Oh. Right, sorry about that @babhishek21 . I did my edits on the master branch of my forked repo.
Thank you very much for the steps you gave. I will definitely follow that next time.

**Comment by ktilcu** [comment]
@JJEEGG2211 whoa. There are a lot of changes smushed into your PR. Here's what I suggest. Copy the files you changed. Then run
```shell
git fetch
git reset --hard
```
Then copy your files back in and do:
```shell
git add .
git commit
git push origin/HEAD
```
You should get an error about non fast forward changes or something. If you are sure that your current local files are right you can run.

```shell
git push origin/HEAD -f
```

That will force your local changes to your fork and automatically update this PR.

**Comment by JJEEGG2211** [comment]
Hi @ktilcu that was really weird. The changes in my forked repo couldn't be detected in the pull request.
I followed the suggestion you gave and hopefully I did it correctly now. 🤞 

Thanks!

**Comment by ktilcu** [comment]
Way to go!

**Comment by ktilcu** [comment]
It would help us if you made an issue for you new method too. Thank you!

**Comment by JJEEGG2211** [comment]
Thanks @ktilcu and @babhishek21 
I'll add the new issue. Learned so much already. 😉

**Pull request merged**
