### PR TITLE
Refactor firstUniqueChar and add vowelCount methods

### PR DESCRIPTION
**Pull request by cjhaviland**
- [x] Running `yarn lint` does not trigger any linter warnings
- [x] The test of the method you have fixed is passing
- [x] You have written a new skeleton method for someone else to work on!

### CODE REVIEW

**Comment by BlakeGuilloud** [comment]
Looks really nice @cjhaviland ! Great job. If you don't mind doing a couple of things for me:
1. Wrap your vowelCount test into a single "describe" block- we are trying to move to having a single test suite for each method. It makes things easier to read and follow when running tests.
2. Pull in the latest master and resolve merge conflicts.

Thanks!!

**Comment by cjhaviland** [comment]
@BlakeGuilloud I am not sure if I did this right XD hopefully that works. Let me know what else I might need to do.

**Comment by BlakeGuilloud** [comment]
You will need to pull from the upstream master into your fork.

**Comment by BlakeGuilloud** [comment]
Boom. looks like you got it; however, there has been a new linting rule introduced to not mix tabs and spaces, if you don't mind running `yarn lint` and fixing that error, then I will merge this in! Thanks for your contribution!

**Comment by BlakeGuilloud** [comment]
@cjhaviland I'm going to go ahead and merge this in myself. I'll resolve the conflicts. Thanks for your contribution!! If you feel like making a new "Issue" for your vowelCount method, that would be an awesome way to give back! Thanks!!

**Pull request merged**
